version: '2'
services:
    jhipstersampleapplicationddddd-app:
        image: jhipstersampleapplicationddddd
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipstersampleapplicationddddd-mysql:3306/jhipstersampleapplicationddddd?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipstersampleapplicationddddd-mysql:
        extends:
            file: mysql.yml
            service: jhipstersampleapplicationddddd-mysql
